from pathlib import Path
from typing import Tuple, List
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from langchain.docstore.document import Document

class Retriever:
    """
    Loads the FAISS index (generated by ingest/build_vectorstore.py)
    and exposes get_context() to retrieve context and sources.
    """
    def __init__(self, faiss_subpath: str | None = None):
        base = Path(__file__).resolve().parents[1]  # .../backend
        faiss_dir = Path(faiss_subpath) if faiss_subpath else base / "data" / "vectorstore" / "faiss"
        if not faiss_dir.exists():
            raise RuntimeError(f"No se encontró el índice FAISS en: {faiss_dir}")

        # MULTILINGUAL (ES/EN) embedding so that Spanish questions work with English docs
        self.embed = HuggingFaceEmbeddings(
            model_name="sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
        )
        # allow_dangerous_deserialization required by FAISS.load_local
        self.vs: FAISS = FAISS.load_local(str(faiss_dir), self.embed, allow_dangerous_deserialization=True)

    def get_context(self, question: str, k: int = 6) -> Tuple[str, List[str], list[Document]]:
        docs = self.vs.max_marginal_relevance_search(question, k=k, lambda_mult=0.3)
        context = "\n\n".join([d.page_content for d in docs])
        sources = list({d.metadata.get("source", "unknown") for d in docs})
        return context, sources, docs

